# Generated by Django 2.2.6 on 2019-11-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bomonka_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomonka_forum.Profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
